### ISSUE TITLE
Contributing to this project

### ISSUE THREAD

**Issue by rajivvishwa** [bamhm182/WGU-Plus#13]
Hi, as mentioned in the Readme file, I cloned the project and made changes locally. I cannot do a pull request as I don't have the permissions to create a new branch or publish directly to master. I created a file that you can find [here](https://gist.github.com/rajivvishwa/cb8288ac06ca38d3b11c554f9611c770). 

Let me know how I can contribute.

**Comment by bamhm182** [comment]
Already added. Closing ticket.
