### ISSUE TITLE
request: add C170

### ISSUE THREAD

**Issue by v-steve** [bamhm182/WGU-Plus#15]
https://github.com/v-steve/WGU-Plus/blob/master/src/9780002.txt - I added the links in the file that should be appropriate or helpful for the course.

**Comment by Gwindalmir** [comment]
I created a PR #16 that adds it, but I didn't see your links until now.

**Comment by v-steve** [comment]
Thank you!

**Comment by bamhm182** [comment]
Sorry it took forever. I tore down the server I had auto-building WGU+ and life got busy, so simple stuff like this wasn't so simple. I got a new pipeline set up tonight and there's no reason that'll ever go away, so future simple stuff like this should be a lot quicker.
