### ISSUE TITLE
CBT Nuggets Logo

### ISSUE THREAD

**Issue by nivek1385** [bamhm182/WGU-Plus#4]
If you wanted to add the CBT Nuggets to the images, it's available in SVG form at [https://www.cbtnuggets.com/static/v130/images/header/cbtn_logo.svg]

**Comment by bamhm182** [comment]
Sounds good! There were a couple other websites I frequently saw when adding all of my classes last night
 I will add more icons soon.

**Comment by bamhm182** [comment]
I've added an icon for CBT Nuggets, as well as a few other types of classes. I don't have it written anywhere, but the type of class should be all one word. I will add that to the documentation now. Thank you for your submission! :)

**Comment by nivek1385** [comment]
Yeah, I discovered this right as I was heading to bed last night. I figured I'd add other classes sometime today, but haven't been at the computer until now and I really should study right now. I'll add more later.
