### ISSUE TITLE
Google Drive Integration

### ISSUE THREAD

**Issue by ZacharyDavidSaunders** [bamhm182/WGU-Plus#9]
What do you guys think about supporting the <a href="https://drive.google.com/open?id=0B1S7OJNChk1-cWhwNWZTb2JNY1E" target="_blank">WGU student Google Drive</a> as a resource type? It has lots of resources organized by class. We would have to somehow match the currCourse id to the drive folder name, but we may be able to modify the drive to make this easier.

We could use this as the icon: 
http://icons.iconarchive.com/icons/dakirby309/simply-styled/128/Google-Drive-icon.png
![Google Drive Icon](http://icons.iconarchive.com/icons/dakirby309/simply-styled/128/Google-Drive-icon.png "Google Drive Icon")

**Comment by bamhm182** [comment]
I stumbled across another drive with some information in it, but I've just been adding the information in the drive rather than the drive itself in case people are not able to get access to it. That said, I'm not opposed to adding this in.

**Comment by ZacharyDavidSaunders** [comment]
Okay, sounds good. I'll close this issue for now. We can add this later if we find that it's needed.
